# Generated by Django 4.0.3 on 2022-03-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ButWare', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Товары'},
        ),
    ]
