# Generated by Django 4.0.3 on 2022-03-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ButWare', '0004_alter_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системы',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
