# Generated by Django 4.0.3 on 2022-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ButWare', '0005_systems'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Статус объекта',
                'verbose_name_plural': 'Статусы объектов',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
