# Generated by Django 4.0.3 on 2022-03-11 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ButWare', '0006_statusobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('address', models.CharField(max_length=800, verbose_name='Адрес')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Клиент')),
                ('contact_face', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='Генподрядчик')),
                ('designer', models.CharField(blank=True, max_length=200, verbose_name='Дизайнер')),
                ('dir_client_project', models.CharField(blank=True, max_length=200, verbose_name='Руководитель проекта заказчика')),
                ('developer', models.CharField(blank=True, max_length=200, verbose_name='Проектировщик')),
                ('foroman', models.CharField(blank=True, max_length=200, verbose_name='Прораб')),
                ('electrician', models.CharField(blank=True, max_length=200, verbose_name='Электрик')),
                ('ovik', models.CharField(blank=True, max_length=200, verbose_name='ОВиК')),
                ('contract', models.CharField(blank=True, max_length=200, verbose_name='Договор')),
                ('dir_butler_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель проекта Butler')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ButWare.statusobject', verbose_name='Статус')),
                ('system', models.ManyToManyField(to='ButWare.systems', verbose_name='Системы')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
