# Generated by Django 4.0.3 on 2022-03-11 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ButWare', '0007_objectscurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы смет',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_doc', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ButWare.objectscurrent', verbose_name='Объект')),
                ('status_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ButWare.statusestimate')),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
            },
        ),
    ]
