# Generated by Django 4.0.3 on 2022-03-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ButWare', '0008_statusestimate_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ButWare.estimate', verbose_name='Смета')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ButWare.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатуры смет',
            },
        ),
    ]
